### ISSUE TITLE
Editing colours on pills

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#1001]
## Describe the bug

When editing the colours on the pills/bullets the sample displayed is using the old transparent colours rather than the saturated colours of the new design.

## To Reproduce

_Steps to reproduce the behavior:_

1. Go to Communities tab from the side menu
2. Select Edit from one of the Communities listed
3. Click on the colour selection tool and adjust to a new colour
4. See the sample pill/bullet change to a transparent background with coloured text
5. Clicking Save will update the pill to the desired solid background

## Expected behavior

The pill/bullet should show the selected colour as a solid background while using the colour selection tool

## Screenshot

<img width="1126" alt="Screenshot 2024-10-25 at 11 59 16 AM" src="https://github.com/user-attachments/assets/5e6c090f-fcec-45c2-837d-caf8b06d7909">

**Comment by ferrisoxide** [comment]
@SishaMish This has been fixed and is ready for testing.

**Comment by ferrisoxide** [comment]
@SishaMish This is ready for QA

**Comment by SishaMish** [comment]
@ferrisoxide 

QA'd and passed.
