### ISSUE TITLE
Colours that are not showing text clearly

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#1002]
## Describe the bug

Some colours are showing text that is too dark to read clearly on light mode

## Example Hex Colours

008C8C
2E74BA
009BCC
914BB4

## Screenshots

<img width="437" alt="Screenshot 2024-10-25 at 12 12 17 PM" src="https://github.com/user-attachments/assets/7f7cf0ea-35af-4138-85ed-ba4a5971831d">

**Comment by ferrisoxide** [comment]
@SishaMish Fix is on staging. NB the colours are probably not perfect, in that the luminance "breakpoint" (where we swap between light and dark text) might be a bit off for bright pinks:

![image](https://github.com/user-attachments/assets/6d2691fc-7d35-4881-bbaa-e623469aeb69)

I think we're in "good enough" territory though. Not completely sure if the text colour for the "Not for Profit" is more or less readable than before, but I'll leave that to you to decide.

**Comment by ferrisoxide** [comment]
@SishaMish This is ready for QA

**Comment by SishaMish** [comment]
@ferrisoxide 

QA'd and will pass it.
