### ISSUE TITLE
'Tool Tip' remains visible after clicking on a new menu item

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#536]
## Describe the bug
On the Transition Cards page, when I click on a Transition Card to view it, and then use the back button on my browser, the black 'Tool Tip' remains visible. When I click on another transition card, and use the back button to return to the list, multiple 'Tool Tips' are now visible. This continues to happen the more Transition cards I view and return to the list.

## To Reproduce
1. Go to 'Transition Cards'
2. Click on any Transition Card
3. Once loaded, use the back button on browser
4. When back at the Transition Card list, the 'Tool Tip' stays highlighted

## Expected behavior
When navigating into a Transition Card and back out to the Transition card list, I expect the Tool Tip to clear and not remain visible.

## Screenshots
![Screen Shot 2021-02-21 at 4 21 53 pm](https://user-images.githubusercontent.com/39264459/108616848-4993ba00-7461-11eb-8212-f3df9e4b90e8.png)

## Desktop (please complete the following information):
 - OS: Mac 10.15.7 
 - Browser Chrome
 - Version 88.0.4324.150

## Additional context
Also occurring on Windows 10, Browser Microsoft Edge

**Comment by ferrisoxide** [comment]
No longer an issue after Gen-2. Closing.
