### ISSUE TITLE
Select Sub System Tags multiplies when going into Transition cards

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#538]
## Describe the bug
From the Transition Card list, when I view a Transition Card and return to the Transition Card list, a new 'Select Subsystems Tags' button appears at the top of the screen. Each time I view a new Transition card, another button appears.

## To Reproduce
1. Go to 'Transition Cards'
2. Click on and Transition Card from the list
3. Click the back button on the browser
4. A new 'Select Subsystems Tags' text box appears at the top of the screen

## Expected behavior
I expect there to be only one 'Select Subsystems Tags' box at the top of the screen.

## Screenshots
![Screen Shot 2021-02-21 at 4 10 56 pm](https://user-images.githubusercontent.com/39264459/108617037-e571f580-7462-11eb-84d8-87ae94878936.png)

## Desktop (please complete the following information):
 - OS: Mac 10.15.7 
 - Browser Chrome
 - Version 88.0.4324.150

**Comment by ferrisoxide** [comment]
No longer an issue post Gen-2. Closing.
