### ISSUE TITLE
No ability to scroll on Transition Card

### ISSUE THREAD

**Issue by TuddlesT** [EventideSystems/tool_for_systemic_change#541]
## Describe the bug
If the user expands the 'Description' text box by dragging from the bottom right, it will be obscured by the line the 'Next' Button is on. If you begin to type on the lines that are obscured, the both 'Name' and 'Description' text boxes will move up, obscuring the 'Name' box with the header.

## To Reproduce
1. Go to 'Transition Cards'
2. Click on 'Create New'
3. Expand 'Description' text box by dragging the bottom right corner (first screenshot)
4. Type in the lines obscured by next button
5. See error (second screenshot)

## Expected behavior
Either the bar contained the 'Next' button would move down to accommodate for the expanded description box, or a scroll bar would appear on the right to scroll up to the 'Name' text box (however this wouldn't be as functional)

## Screenshots
![image](https://user-images.githubusercontent.com/12377749/108617655-29b3c480-7468-11eb-955e-4b54db228f23.png)
![image](https://user-images.githubusercontent.com/12377749/108617732-96c75a00-7468-11eb-8435-930e477e978e.png)

## Desktop:
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.182

## Additional Information
Going to a different tab and back in moves the bar with the 'Next' button

**Comment by ferrisoxide** [comment]
No longer relevant. UX has changed with Gen-2
