### ISSUE TITLE
Transition Cards tab titles not aligned 

### ISSUE THREAD

**Issue by TuddlesT** [EventideSystems/tool_for_systemic_change#542]
## Describe the bug
When creating a new transition card, the text on the tabs indicating each step aren't centred or aligned.

## To Reproduce
1. Go to 'Transition Cards'
2. Click 'Create New'
3. See error

## Expected behavior
The titles would be in the centre of each tab and aligned to each other

## Screenshots
![image](https://user-images.githubusercontent.com/12377749/108617873-764bcf80-7469-11eb-86d1-56a7e38e4d31.png)

## Desktop (please complete the following information):
- OS: Windows 10
- Browser: Chrome
- Version: 88.0.4324.182

**Comment by ferrisoxide** [comment]
Closing. Not used post Gen-2
