### ISSUE TITLE
Stuttering on Ecosystem Map

### ISSUE THREAD

**Issue by TuddlesT** [EventideSystems/tool_for_systemic_change#544]
## Describe the bug
When dragging the ecosystem map around, the map will seem to stutter between two points quickly. Zooming in lessens the issue, while zooming out causes the map to stutter further until it disappears entirely, which can only be fixed by resetting

## To Reproduce
1. Go to 'Transition Cards'
2. Click on 'Ecosystem Maps'
3. Drag map around

## Expected behavior
The map should move smoothly without stuttering on any zoom

## Desktop:
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.182

**Comment by ferrisoxide** [comment]
No longer an issue post Gen-2. Closing.
