### ISSUE TITLE
When the mouse is hovering over a clickable link a double Tool Tip appears

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#546]
## Describe the bug
When holding the mouse pointer over a clickable link, a Tool Tip appears. If the mouse moves slightly a secondary Tool Tip appears with the same information.

## To Reproduce
1. Go to 'Transition Cards'
2. Hover mouse pointer over first clickable link on the list
3. Wait for Tool Tip to pop up
4. Move mouse slightly, but not off the link
5. A secondary Tool Tip appears

## Expected behavior
I expect to only see one Tool Tip when hovering the mouse pointer over a link.

## Screenshots
![Screen Shot 2021-02-21 at 6 18 15 pm](https://user-images.githubusercontent.com/39264459/108619034-258ca480-7472-11eb-80da-b50408ef2ea6.png)

## Desktop (please complete the following information):
 - OS: Mac
 - Browser Safari
 - Version  14.0.3

**Comment by ferrisoxide** [comment]
No longer an issue post Gen-2. Closing.
