### ISSUE TITLE
Safari - Creating Transition Card Problem and Community

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#547]
## Describe the bug
When creating a new Transition Card, on the screen for entering Wicked Problem/Opportunity, after selecting 'Create New' and filling in the pop-up box, the newly created Problem is not automatically selected in the dropdown menu. This menu is left blank requiring the user to manually select the newly created Problem. The same issue occurs on the next screen for entering Community. If the user does not manually check these options, then they will not be able to save the Transition Card. This issue appears only to happen in Safari, and did not occur in Chrome or Firefox.

## To Reproduce
After creating a new Transition Card and entering a Name and Description
1. Go to Wicked Problem/Opportunity tab
2. Click on 'Create New...'
3. Complete pop-up box with new Problem and save
4. The Select Wicked Problem text box is blank

1. Go to Community tab
2. Click on 'Create New...'
3. Complete pop-up box with new Community and save
4. The Select Community text box is blank

## Expected behavior
I expect, after entering a new Problem and saving it via the pop up box, that the new Problem will be automatically selected in the dropdown menu. I expect this behaviour to also happen when adding a new Community on the next tab after this one.

## Screenshots
![Screen Shot 2021-02-21 at 10 00 23 pm](https://user-images.githubusercontent.com/39264459/108623687-38ae6d00-7490-11eb-826c-c788b2877d94.png)

## Desktop (please complete the following information):
 - OS: Mac
 - Browser Safari
 - Version 14.0.3

**Comment by ferrisoxide** [comment]
No longer relevant.
