### ISSUE TITLE
Deep copy of Initiatives not copying characteristics

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#982]
### Describe the issue
When creating a Deep Copy of an Initiative a Shallow Copy is created. The Deep Copy does not include characteristic history.

### Expected behaviour
When creating a Deep Copy of an Initiative that contains characteristic activity (comments etc), I expect the characteristic activity to be included in the copy.

### More Information
I have tested this on both staging and production with the same results.
The Production account used for testing was QA_526_SishaMish
The Transition Card copied is Disaster Resilience Greenville
The shallow and deep copies created from this Transition Card are named 'Shallow copy' and 'Deep copy' respectively.

### Screenshots
Original Transition Card

![Image](https://github.com/user-attachments/assets/ab6ff80d-f044-4ab1-84ec-625d2f75eeed)

Deep Copy of the same Transition Card

![Image](https://github.com/user-attachments/assets/a42ae75c-9dc8-46ab-aaee-bceda686b818)

**Comment by ferrisoxide** [comment]
### NOTES TO QA

@SishaMish This is on production and ready for QA there. The main test will be to make sure that comments and state are transferred. Suggested steps:

1. Pick an impact card with a decent amount of activity recorded against it (state and comments)
2. Run the "Comments Report" report for the chosen card, using today's date and 'actual' as the parameters
3. Visit the card and select the "Copy" button

![image](https://github.com/user-attachments/assets/a823e523-6433-49b5-99d4-37ba81826f45)

4. On the "Copy Transition Card" select "Deep copy" and then click the "Copy Transition Card" button (note the new name of the copied card)

![image](https://github.com/user-attachments/assets/e7962bab-7ac2-406d-ac67-770db25d01cc)

5. Once the copy completes, run the "Comments Report" again but this time select the copied card.
6. Compare the two reports. The data should be the same.

**Comment by SishaMish** [comment]
@ferrisoxide 

I have tested this using the method described above using the account 'Test Account' and creating a deep copy of the transition card 'Disaster Resilience Greenville'.

This passed QA, but with a couple of notes:

1. The copy reordered the initiatives in to alphabetical order, so on initial inspection it appeared to be missing the first initiative, but with a closer look all initiatives were accounted for. Obviously not a bug, but was unsure if this was usual behaviour.
2. On the Reports page, the drop down box to select the transition card is missing it's label. I will create a new bug report for this if you would like me to.

![Screenshot 2024-11-27 at 1 04 50 PM](https://github.com/user-attachments/assets/83301299-2efa-47b0-9fcd-b98d7edca4ca)

**Comment by ferrisoxide** [comment]
@SishaMish 

> 1. The copy reordered the initiatives in to alphabetical order, so on initial inspection it appeared to be missing the first initiative, but with a closer look all initiatives were accounted for. Obviously not a bug, but was unsure if this was usual behaviour.
> 2. On the Reports page, the drop down box to select the transition card is missing it's label. I will create a new bug report for 
this if you would like me to.

Fix is on production and ready for QA.

**Comment by SishaMish** [comment]
@ferrisoxide 

QA'd and passed. Closing this ticket.
